[platformio]
default_envs = d1_mini

[env]
test_framework = unity

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
board_build.ldscript = eagle.flash.4m2m.ld
lib_deps =
  siruli/MAX6675@^2.1.0
  br3ttb/PID@^1.2.1
  adafruit/Adafruit RGB LCD Shield Library@^1.2.2

[env:native]
platform = native
build_flags =
  -DUNIT_TEST
  -Itest/mocks
test_build_src = yes
build_src_filter =
  -<*>
  +<program_manager.cpp>
